
-- LISTAR TABLAS Y SUS SULTIMAS ACTUALIZACIONES --

SELECT * FROM all_objects ao WHERE ao.OBJECT_TYPE = 'TABLE' AND ao.OWNER = 'INFOCENT';

SELECT * FROM all_tab_modifications;

-- ULTIMA ACTUALIZACION DE UNA TABLA EN ESPECIFICO --

SELECT SCN_TO_TIMESTAMP(MAX(ora_rowscn)) AS "ACTUALIZACION" FROM V_NOMINA_H; 


