SELECT DISTINCT A.CEDULA AS IDENTIFICATION,A."NOMBRES Y APELLIDOS" AS NAME, A."FECHA INGRESO" AS ADMISSION_DATE,
A."DESCRIPCION CARGO" AS EMPLOYMENT,A.LOCALIDAD AS COMPANY,A."UNIDAD ORGANIZATIVA" AS COST_CENTER, A."CODIGO DISTRIBUCION NOMINA" AS "ID_GEO_LOC",
A."CODIGO DE UNIDAD" AS ID_CECO,A."UNIDAD ORGANIZATIVA" AS CECODESCRI,A."TIPO NOMINA" AS PAYROLL_TYPE,
A."ENTIDAD DE TRABAJO" AS COMPANY_ID,A.CEDULA AS IDENTIFICATION_S,A.FICHA AS INDEX_CARD,A.NOMBRES AS NAMES,A.NOMBRE1 AS "NAME1",A.NOMBRE2 AS "NAME2",
A.APELLIDOS AS LAST_NAME,A.APELLIDO1 AS "LAST_NAME1",A.APELLIDO2 AS "LAST_NAME2",A."FECHA DE NACIMIENTO" AS "BIRTH_DATE", A.NACIONALIDAD AS "NATIONALITY", A.SEXO AS "GENDER",A."ESTADO CIVIL" AS "CIVIL_STATUS",
A."HABILIDAD MANUAL" AS "MANUAL_SKILL",A.TELEFONO1 AS "TELEPHONE1", A.TELEFONO2 AS "TELEPHONE2", A.EMAIL AS "EMAIL",A.DIRECCION AS "ADDRESS",/*A.PAIS AS "COUNTRY",A.ESTADO AS "STATE",*/
A.CIUDAD AS "POPULATED",A."CODIGO POSTAL" AS "POSTAL_CODE",A.NRO_RIF AS RIF,
CASE WHEN A.ESTATUS =  'ACTIVO' THEN '1' ELSE '9' END AS ACTIVITI,
A."CODIGO SITUACION" AS SITUATION,

-----------------------------------------------------CALCULO MONTO IMPUESTO-----------------------------------------------------

case when ((SELECT (NVL(NMM014.RETE01,0)+NVL(NMM014.RETE02,0)+NVL(NMM014.RETE03,0)+NVL(NMM014.RETE04,0)+
NVL(NMM014.RETE05,0)+NVL(NMM014.RETE06,0)+NVL(NMM014.RETE07,0)+NVL(NMM014.RETE08,0)+
NVL(NMM014.RETE09,0)+NVL(NMM014.RETE10,0)+NVL(NMM014.RETE11,0)+NVL(NMM014.RETE12,0))*-1
FROM NMM014
WHERE NMM014.TRAB_FICTRA="FICHA"
AND NMM014.CIA_CODCIA="ENTIDAD DE TRABAJO"
AND ANOIMP=TO_CHAR(SYSDATE,'YYYY'))-
(case when (SELECT SUM(X.MONCTO) 
FROM NMM024 X
WHERE X.FPRO_ANOCAL=TO_CHAR(SYSDATE,'YYYY')
AND X.CTO_CODCTO =1150
AND X.cia_codcia="ENTIDAD DE TRABAJO" and X.trab_fictra="FICHA")is null then 0 else (SELECT SUM(X.MONCTO) 
FROM NMM024 X
WHERE X.FPRO_ANOCAL=TO_CHAR(SYSDATE,'YYYY')
AND X.CTO_CODCTO =1150
AND X.cia_codcia="ENTIDAD DE TRABAJO" and X.trab_fictra="FICHA") end )) is null then 0 else 
((SELECT (NVL(NMM014.RETE01,0)+NVL(NMM014.RETE02,0)+NVL(NMM014.RETE03,0)+NVL(NMM014.RETE04,0)+
NVL(NMM014.RETE05,0)+NVL(NMM014.RETE06,0)+NVL(NMM014.RETE07,0)+NVL(NMM014.RETE08,0)+
NVL(NMM014.RETE09,0)+NVL(NMM014.RETE10,0)+NVL(NMM014.RETE11,0)+NVL(NMM014.RETE12,0))*-1
FROM NMM014
WHERE NMM014.TRAB_FICTRA="FICHA"
AND NMM014.CIA_CODCIA="ENTIDAD DE TRABAJO"
AND ANOIMP=TO_CHAR(SYSDATE,'YYYY'))-
(case when (SELECT SUM(X.MONCTO) 
   FROM NMM024 X
   WHERE X.FPRO_ANOCAL=TO_CHAR(SYSDATE,'YYYY')
   AND X.CTO_CODCTO =1150
   AND X.cia_codcia="ENTIDAD DE TRABAJO" and X.trab_fictra="FICHA")is null then 0 else (SELECT SUM(X.MONCTO) 
   FROM NMM024 X
   WHERE X.FPRO_ANOCAL=TO_CHAR(SYSDATE,'YYYY')
   AND X.CTO_CODCTO =1150
   AND X.cia_codcia="ENTIDAD DE TRABAJO" and X.trab_fictra="FICHA") end )) end  AS "TOT_IMP",  
   
-----------------------------------------------------CALCULO MONTO REMUNERADO---------------------------------------------------    

case when (SELECT NVL(NMM014.REMP01,0)+NVL(NMM014.REMP02,0)+NVL(NMM014.REMP03,0)+NVL(NMM014.REMP04,0)+
 NVL(NMM014.REMP05,0)+NVL(NMM014.REMP06,0)+NVL(NMM014.REMP07,0)+NVL(NMM014.REMP08,0)+
 NVL(NMM014.REMP09,0)+NVL(NMM014.REMP10,0)+NVL(NMM014.REMP11,0)+NVL(NMM014.REMP12,0)
FROM NMM014
WHERE NMM014.TRAB_FICTRA="FICHA"
  AND NMM014.CIA_CODCIA="ENTIDAD DE TRABAJO"
  AND ANOIMP=TO_CHAR(SYSDATE,'YYYY')) is null then 0 else (SELECT NVL(NMM014.REMP01,0)+NVL(NMM014.REMP02,0)+NVL(NMM014.REMP03,0)+NVL(NMM014.REMP04,0)+
 NVL(NMM014.REMP05,0)+NVL(NMM014.REMP06,0)+NVL(NMM014.REMP07,0)+NVL(NMM014.REMP08,0)+
 NVL(NMM014.REMP09,0)+NVL(NMM014.REMP10,0)+NVL(NMM014.REMP11,0)+NVL(NMM014.REMP12,0)
FROM NMM014
WHERE NMM014.TRAB_FICTRA="FICHA"
  AND NMM014.CIA_CODCIA="ENTIDAD DE TRABAJO"
  AND ANOIMP=TO_CHAR(SYSDATE,'YYYY')) end AS "TOT_REMU",
  
-----------------------------------------------------CALCULO MONTO VACACIONES---------------------------------------------------

ROUND((
case when (select DECODE(TRUNC(MONTHS_BETWEEN(sysdate,F_INGRESO)/12),0,(21+15),1,(23+15),2,(23+15+1),3,(23+15+2),4,(23+15+3),5,(23+15+4),
												  6,(26+15+5),7,(26+15+6),8,(26+15+7),9,(26+15+8),10,(26+15+9),
												 11,(29+15+10),12,(29+15+11),13,(29+15+12),14,(29+15+13),15,(29+15+14),
												 16,(33+15+15),17,(33+15+15),18,(33+15+15),19,(33+15+15),20,(33+15+15),
												 null,(0),68) CANT_ANOS1                                                        
 FROM TA_RELACION_LABORAL TA
WHERE TA.FICHA =A.FICHA
  AND TA.ID_EMPRESA=A."ENTIDAD DE TRABAJO"
  AND TO_CHAR(TA.F_INGRESO,'YYYY')<TO_CHAR(SYSDATE,'YYYY')
  AND TA.FICHA||TA.ID_EMPRESA  not IN (SELECT M023.TRAB_FICTRA||M023.CIA_CODCIA
										 FROM NMM023 M023/*HIST. ENCABEZADO */
										WHERE M023.FPRO_ANOCAL=TO_CHAR(SYSDATE,'YYYY')
										  AND M023.PROC_TIPPRO=4
										  AND M023.TONETO>0) ) is null then 0 else 
 (select DECODE(TRUNC(MONTHS_BETWEEN(sysdate,F_INGRESO)/12),0,(21+15),1,(23+15),2,(23+15+1),3,(23+15+2),4,(23+15+3),5,(23+15+4),
												  6,(26+15+5),7,(26+15+6),8,(26+15+7),9,(26+15+8),10,(26+15+9),
												 11,(29+15+10),12,(29+15+11),13,(29+15+12),14,(29+15+13),15,(29+15+14),
												 16,(33+15+15),17,(33+15+15),18,(33+15+15),19,(33+15+15),20,(33+15+15),
												 null,(0),68) CANT_ANOS1                                                        
 FROM TA_RELACION_LABORAL TA
WHERE TA.FICHA =A.FICHA
  AND TA.ID_EMPRESA=A."ENTIDAD DE TRABAJO"
  AND TO_CHAR(TA.F_INGRESO,'YYYY')<TO_CHAR(SYSDATE,'YYYY')
  AND TA.FICHA||TA.ID_EMPRESA  not IN (SELECT M023.TRAB_FICTRA||M023.CIA_CODCIA
										 FROM NMM023 M023/*HIST. ENCABEZADO */
										WHERE M023.FPRO_ANOCAL=TO_CHAR(SYSDATE,'YYYY')
										  AND M023.PROC_TIPPRO=4
										  AND M023.TONETO>0) ) end  
										  *
(SELECT MAX(NMM004.SUEDIA)
  FROM NMM004
 WHERE NMM004.TRAB_FICTRA="FICHA"
   AND NMM004.CIA_CODCIA="ENTIDAD DE TRABAJO")),2)  AS "TOTAL_VACAC",
   
---------------------------------------------------CALCULO MONTO DE UTILIDADES--------------------------------------------------

ROUND(
((case when (select DECODE(TRUNC(MONTHS_BETWEEN(TO_DATE('31/12/2020','DD/MM/YYYY'),F_INGRESO)),
							 0,(0),1,(10),2,(20),3,(30),4,(40),5,(50),
							 6,(60),7,(70),8,(80),9,(90),10,(100),
							11,(110),null,(0),120) CANT_ANOS1                                                        
FROM TA_RELACION_LABORAL TA
WHERE TA.FICHA =A.FICHA
AND TA.ID_EMPRESA=A."ENTIDAD DE TRABAJO"
AND TO_CHAR(TA.F_INGRESO,'YYYY')<TO_CHAR(SYSDATE,'YYYY')) is null then 0 else 
(select DECODE(TRUNC(MONTHS_BETWEEN(TO_DATE('31/12/2020','DD/MM/YYYY'),F_INGRESO)),
							 0,(0),1,(10),2,(20),3,(30),4,(40),5,(50),
							 6,(60),7,(70),8,(80),9,(90),10,(100),
							11,(110),null,(0),120) CANT_ANOS1                                                        
FROM TA_RELACION_LABORAL TA
WHERE TA.FICHA =A.FICHA
AND TA.ID_EMPRESA=A."ENTIDAD DE TRABAJO"
AND TO_CHAR(TA.F_INGRESO,'YYYY')<TO_CHAR(SYSDATE,'YYYY')) end)  
*
( (case when (SELECT NVL(NMM014.REMP01,0)+NVL(NMM014.REMP02,0)+NVL(NMM014.REMP03,0)+NVL(NMM014.REMP04,0)+
 NVL(NMM014.REMP05,0)+NVL(NMM014.REMP06,0)+NVL(NMM014.REMP07,0)+NVL(NMM014.REMP08,0)+
 NVL(NMM014.REMP09,0)+NVL(NMM014.REMP10,0)+NVL(NMM014.REMP11,0)+NVL(NMM014.REMP12,0)
FROM NMM014
WHERE NMM014.TRAB_FICTRA="FICHA"
  AND NMM014.CIA_CODCIA="ENTIDAD DE TRABAJO"
  AND ANOIMP=TO_CHAR(SYSDATE,'YYYY')) is null then 0 else (SELECT NVL(NMM014.REMP01,0)+NVL(NMM014.REMP02,0)+NVL(NMM014.REMP03,0)+NVL(NMM014.REMP04,0)+
 NVL(NMM014.REMP05,0)+NVL(NMM014.REMP06,0)+NVL(NMM014.REMP07,0)+NVL(NMM014.REMP08,0)+
 NVL(NMM014.REMP09,0)+NVL(NMM014.REMP10,0)+NVL(NMM014.REMP11,0)+NVL(NMM014.REMP12,0)
FROM NMM014
WHERE NMM014.TRAB_FICTRA="FICHA"
  AND NMM014.CIA_CODCIA="ENTIDAD DE TRABAJO"
  AND ANOIMP=TO_CHAR(SYSDATE,'YYYY')) end)             
  +
  (SELECT ROUND( ROUND(MONTHS_BETWEEN(TO_DATE('31/12/'||(to_char(SYSDATE,'YYYY')),'DD/MM/YYYY'),SYSDATE),0)*(MAX(NMM004.SUEDIA)*30),0)	                                                
FROM NMM004
WHERE NMM004.TRAB_FICTRA="FICHA"
  AND NMM004.CIA_CODCIA="ENTIDAD DE TRABAJO")
+
(ROUND(
(case when (select DECODE(TRUNC(MONTHS_BETWEEN(sysdate,F_INGRESO)/12),0,(21+15),1,(23+15),2,(23+15+1),3,(23+15+2),4,(23+15+3),5,(23+15+4),
											  6,(26+15+5),7,(26+15+6),8,(26+15+7),9,(26+15+8),10,(26+15+9),
											 11,(29+15+10),12,(29+15+11),13,(29+15+12),14,(29+15+13),15,(29+15+14),
											 16,(33+15+15),17,(33+15+15),18,(33+15+15),19,(33+15+15),20,(33+15+15),
											 null,(0),68) CANT_ANOS1                                                        
FROM TA_RELACION_LABORAL TA
WHERE TA.FICHA =A.FICHA
AND TA.ID_EMPRESA=A."ENTIDAD DE TRABAJO"
AND TO_CHAR(TA.F_INGRESO,'YYYY')<TO_CHAR(SYSDATE,'YYYY')
AND TA.FICHA||TA.ID_EMPRESA  not IN (SELECT M023.TRAB_FICTRA||M023.CIA_CODCIA
									 FROM NMM023 M023/*HIST. ENCABEZADO */
									WHERE M023.FPRO_ANOCAL=TO_CHAR(SYSDATE,'YYYY')
									  AND M023.PROC_TIPPRO=4
									  AND M023.TONETO>0) ) is null then 0 else 
(select DECODE(TRUNC(MONTHS_BETWEEN(sysdate,F_INGRESO)/12),0,(21+15),1,(23+15),2,(23+15+1),3,(23+15+2),4,(23+15+3),5,(23+15+4),
											  6,(26+15+5),7,(26+15+6),8,(26+15+7),9,(26+15+8),10,(26+15+9),
											 11,(29+15+10),12,(29+15+11),13,(29+15+12),14,(29+15+13),15,(29+15+14),
											 16,(33+15+15),17,(33+15+15),18,(33+15+15),19,(33+15+15),20,(33+15+15),
											 null,(0),68) CANT_ANOS1                                                        
FROM TA_RELACION_LABORAL TA
WHERE TA.FICHA =A.FICHA
AND TA.ID_EMPRESA=A."ENTIDAD DE TRABAJO"
AND TO_CHAR(TA.F_INGRESO,'YYYY')<TO_CHAR(SYSDATE,'YYYY')
AND TA.FICHA||TA.ID_EMPRESA  not IN (SELECT M023.TRAB_FICTRA||M023.CIA_CODCIA
									 FROM NMM023 M023/*HIST. ENCABEZADO */
									WHERE M023.FPRO_ANOCAL=TO_CHAR(SYSDATE,'YYYY')
									  AND M023.PROC_TIPPRO=4
									  AND M023.TONETO>0))  end ) 
									  *
(SELECT MAX(NMM004.SUEDIA)
FROM NMM004
WHERE NMM004.TRAB_FICTRA="FICHA"
AND NMM004.CIA_CODCIA="ENTIDAD DE TRABAJO"),2)))/360),2) AS "TOTAL_UTIL",

-----------------------------------------------CALCULO MONTO POR PERCIBIR-------------------------------------------------------      

((SELECT ROUND( ROUND(MONTHS_BETWEEN(TO_DATE('31/12/'||(to_char(SYSDATE,'YYYY')),'DD/MM/YYYY'),SYSDATE),0)*(MAX(NMM004.SUEDIA)*30),0)	
FROM NMM004
WHERE NMM004.TRAB_FICTRA="FICHA"
AND NMM004.CIA_CODCIA="ENTIDAD DE TRABAJO")
+ 
ROUND((
case when (select DECODE(TRUNC(MONTHS_BETWEEN(sysdate,F_INGRESO)/12),0,(21+15),1,(23+15),2,(23+15+1),3,(23+15+2),4,(23+15+3),5,(23+15+4),
										  6,(26+15+5),7,(26+15+6),8,(26+15+7),9,(26+15+8),10,(26+15+9),
										 11,(29+15+10),12,(29+15+11),13,(29+15+12),14,(29+15+13),15,(29+15+14),
										 16,(33+15+15),17,(33+15+15),18,(33+15+15),19,(33+15+15),20,(33+15+15),
										 null,(0),68) CANT_ANOS1                                                        
FROM TA_RELACION_LABORAL TA
WHERE TA.FICHA =A.FICHA
AND TA.ID_EMPRESA=A."ENTIDAD DE TRABAJO"
AND TO_CHAR(TA.F_INGRESO,'YYYY')<TO_CHAR(SYSDATE,'YYYY')
AND TA.FICHA||TA.ID_EMPRESA  not IN (SELECT M023.TRAB_FICTRA||M023.CIA_CODCIA
								 FROM NMM023 M023/*HIST. ENCABEZADO */
								WHERE M023.FPRO_ANOCAL=TO_CHAR(SYSDATE,'YYYY')
								  AND M023.PROC_TIPPRO=4
								  AND M023.TONETO>0) ) is null then 0 else 
(select DECODE(TRUNC(MONTHS_BETWEEN(sysdate,F_INGRESO)/12),0,(21+15),1,(23+15),2,(23+15+1),3,(23+15+2),4,(23+15+3),5,(23+15+4),
										  6,(26+15+5),7,(26+15+6),8,(26+15+7),9,(26+15+8),10,(26+15+9),
										 11,(29+15+10),12,(29+15+11),13,(29+15+12),14,(29+15+13),15,(29+15+14),
										 16,(33+15+15),17,(33+15+15),18,(33+15+15),19,(33+15+15),20,(33+15+15),
										 null,(0),68) CANT_ANOS1                                                        
FROM TA_RELACION_LABORAL TA
WHERE TA.FICHA =A.FICHA
AND TA.ID_EMPRESA=A."ENTIDAD DE TRABAJO"
AND TO_CHAR(TA.F_INGRESO,'YYYY')<TO_CHAR(SYSDATE,'YYYY')) end                                         
								  * 
(SELECT MAX(NMM004.SUEDIA)
FROM NMM004
WHERE NMM004.TRAB_FICTRA="FICHA"
AND NMM004.CIA_CODCIA="ENTIDAD DE TRABAJO")),2)
+
ROUND(
((case when (select DECODE(TRUNC(MONTHS_BETWEEN(TO_DATE('31/12/2020','DD/MM/YYYY'),F_INGRESO)),
						 0,(0),1,(10),2,(20),3,(30),4,(40),5,(50),
						 6,(60),7,(70),8,(80),9,(90),10,(100),
						11,(110),null,(0),120) CANT_ANOS1                                                        
FROM TA_RELACION_LABORAL TA
WHERE TA.FICHA =A.FICHA
AND TA.ID_EMPRESA=A."ENTIDAD DE TRABAJO"
AND TO_CHAR(TA.F_INGRESO,'YYYY')<TO_CHAR(SYSDATE,'YYYY')) is null then 0 else 
(select DECODE(TRUNC(MONTHS_BETWEEN(TO_DATE('31/12/2020','DD/MM/YYYY'),F_INGRESO)),
						 0,(0),1,(10),2,(20),3,(30),4,(40),5,(50),
						 6,(60),7,(70),8,(80),9,(90),10,(100),
						11,(110),null,(0),120) CANT_ANOS1                                                        
FROM TA_RELACION_LABORAL TA
WHERE TA.FICHA =A.FICHA
AND TA.ID_EMPRESA=A."ENTIDAD DE TRABAJO"
AND TO_CHAR(TA.F_INGRESO,'YYYY')<TO_CHAR(SYSDATE,'YYYY')) end)  
*
( (case when (SELECT NVL(NMM014.REMP01,0)+NVL(NMM014.REMP02,0)+NVL(NMM014.REMP03,0)+NVL(NMM014.REMP04,0)+
NVL(NMM014.REMP05,0)+NVL(NMM014.REMP06,0)+NVL(NMM014.REMP07,0)+NVL(NMM014.REMP08,0)+
NVL(NMM014.REMP09,0)+NVL(NMM014.REMP10,0)+NVL(NMM014.REMP11,0)+NVL(NMM014.REMP12,0)
FROM NMM014
WHERE NMM014.TRAB_FICTRA="FICHA"
AND NMM014.CIA_CODCIA="ENTIDAD DE TRABAJO"
AND ANOIMP=TO_CHAR(SYSDATE,'YYYY')) is null then 0 else (SELECT NVL(NMM014.REMP01,0)+NVL(NMM014.REMP02,0)+NVL(NMM014.REMP03,0)+NVL(NMM014.REMP04,0)+
NVL(NMM014.REMP05,0)+NVL(NMM014.REMP06,0)+NVL(NMM014.REMP07,0)+NVL(NMM014.REMP08,0)+
NVL(NMM014.REMP09,0)+NVL(NMM014.REMP10,0)+NVL(NMM014.REMP11,0)+NVL(NMM014.REMP12,0)
FROM NMM014
WHERE NMM014.TRAB_FICTRA="FICHA"
AND NMM014.CIA_CODCIA="ENTIDAD DE TRABAJO"
AND ANOIMP=TO_CHAR(SYSDATE,'YYYY')) end)             
+
(SELECT ROUND( ROUND(MONTHS_BETWEEN(TO_DATE('31/12/'||(to_char(SYSDATE,'YYYY')),'DD/MM/YYYY'),SYSDATE),0)*(MAX(NMM004.SUEDIA)*30),0)	                                                
FROM NMM004
WHERE NMM004.TRAB_FICTRA="FICHA"
AND NMM004.CIA_CODCIA="ENTIDAD DE TRABAJO")
+
(ROUND(
(case when (select DECODE(TRUNC(MONTHS_BETWEEN(sysdate,F_INGRESO)/12),0,(21+15),1,(23+15),2,(23+15+1),3,(23+15+2),4,(23+15+3),5,(23+15+4),
										  6,(26+15+5),7,(26+15+6),8,(26+15+7),9,(26+15+8),10,(26+15+9),
										 11,(29+15+10),12,(29+15+11),13,(29+15+12),14,(29+15+13),15,(29+15+14),
										 16,(33+15+15),17,(33+15+15),18,(33+15+15),19,(33+15+15),20,(33+15+15),
										 null,(0),68) CANT_ANOS1                                                        
FROM TA_RELACION_LABORAL TA
WHERE TA.FICHA =A.FICHA
AND TA.ID_EMPRESA=A."ENTIDAD DE TRABAJO"
AND TO_CHAR(TA.F_INGRESO,'YYYY')<TO_CHAR(SYSDATE,'YYYY')
AND TA.FICHA||TA.ID_EMPRESA  not IN (SELECT M023.TRAB_FICTRA||M023.CIA_CODCIA
								 FROM NMM023 M023/*HIST. ENCABEZADO */
								WHERE M023.FPRO_ANOCAL=TO_CHAR(SYSDATE,'YYYY')
								  AND M023.PROC_TIPPRO=4
								  AND M023.TONETO>0) ) is null then 0 else 
(select DECODE(TRUNC(MONTHS_BETWEEN(sysdate,F_INGRESO)/12),0,(21+15),1,(23+15),2,(23+15+1),3,(23+15+2),4,(23+15+3),5,(23+15+4),
										  6,(26+15+5),7,(26+15+6),8,(26+15+7),9,(26+15+8),10,(26+15+9),
										 11,(29+15+10),12,(29+15+11),13,(29+15+12),14,(29+15+13),15,(29+15+14),
										 16,(33+15+15),17,(33+15+15),18,(33+15+15),19,(33+15+15),20,(33+15+15),
										 null,(0),68) CANT_ANOS1                                                        
FROM TA_RELACION_LABORAL TA
WHERE TA.FICHA =A.FICHA
AND TA.ID_EMPRESA=A."ENTIDAD DE TRABAJO"
AND TO_CHAR(TA.F_INGRESO,'YYYY')<TO_CHAR(SYSDATE,'YYYY')
AND TA.FICHA||TA.ID_EMPRESA  not IN (SELECT M023.TRAB_FICTRA||M023.CIA_CODCIA
								 FROM NMM023 M023/*HIST. ENCABEZADO */
								WHERE M023.FPRO_ANOCAL=TO_CHAR(SYSDATE,'YYYY')
								  AND M023.PROC_TIPPRO=4
								  AND M023.TONETO>0))  end ) 
								  *
(SELECT MAX(NMM004.SUEDIA)
FROM NMM004
WHERE NMM004.TRAB_FICTRA="FICHA"
AND NMM004.CIA_CODCIA="ENTIDAD DE TRABAJO"),2)))/360),2)
+
(case when (SELECT NVL(NMM014.REMP01,0)+NVL(NMM014.REMP02,0)+NVL(NMM014.REMP03,0)+NVL(NMM014.REMP04,0)+
NVL(NMM014.REMP05,0)+NVL(NMM014.REMP06,0)+NVL(NMM014.REMP07,0)+NVL(NMM014.REMP08,0)+
NVL(NMM014.REMP09,0)+NVL(NMM014.REMP10,0)+NVL(NMM014.REMP11,0)+NVL(NMM014.REMP12,0)
FROM NMM014
WHERE NMM014.TRAB_FICTRA="FICHA"
AND NMM014.CIA_CODCIA="ENTIDAD DE TRABAJO"
AND ANOIMP=TO_CHAR(SYSDATE,'YYYY')) is null then 0 else (SELECT NVL(NMM014.REMP01,0)+NVL(NMM014.REMP02,0)+NVL(NMM014.REMP03,0)+NVL(NMM014.REMP04,0)+
NVL(NMM014.REMP05,0)+NVL(NMM014.REMP06,0)+NVL(NMM014.REMP07,0)+NVL(NMM014.REMP08,0)+
NVL(NMM014.REMP09,0)+NVL(NMM014.REMP10,0)+NVL(NMM014.REMP11,0)+NVL(NMM014.REMP12,0)
FROM NMM014
WHERE NMM014.TRAB_FICTRA="FICHA"
AND NMM014.CIA_CODCIA="ENTIDAD DE TRABAJO"
AND ANOIMP=TO_CHAR(SYSDATE,'YYYY')) end)   
) AS "TOTALP"  

FROM ( ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------TRABAJADORES SIN NINGUNA SITUACION------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------

SELECT A.*,
NULL "CODIGO SITUACION",
NULL "SITUACION ACTUAL",
NULL "FECHA INICIO SITUACION", 
NULL "MES INICIO SITUACION",
NULL "FECHA FIN SITUACION"
FROM (SELECT B.ID_EMPRESA AS "ENTIDAD DE TRABAJO",   
D.ID_NOMINA AS "TIPO NOMINA",
A.FICHA,   
E.NUM_IDEN AS "CEDULA",
E.NOMBRE1||' '||E.NOMBRE2||' '||E.APELLIDO1||' '||E.APELLIDO2 AS "NOMBRES Y APELLIDOS",
C.ID_UNIDAD AS "CODIGO DE UNIDAD", 
G.NOMBRE AS "UNIDAD ORGANIZATIVA",
C.ID_CARGO  AS "CODIGO CARGO",     
K.NOMBRE AS "DESCRIPCION CARGO",
SPI_LOOKUP01.sueldo_hist(A.ID_EMPRESA,A.FICHA,'1',sysdate) "SUELDO DIA",
((SPI_LOOKUP01.sueldo_hist(A.ID_EMPRESA,A.FICHA,'1',sysdate)) * 30) "SUELDO",
D.ID_DIS_NOMINA AS "CODIGO DISTRIBUCION NOMINA",     
F.DESSUC "DISTRIBUCION NOMINA",
H.CODLOC "CODIGO LOCALIDAD",
H.DESLO1 "LOCALIDAD",
B.F_INGRESO "FECHA INGRESO",
B.F_CONTRATO "FECHA CONTRATO",
CASE WHEN B.F_RETIRO IS NULL THEN 'ACTIVO' ELSE 'RETIRADO' END AS ESTATUS,
E.NOMBRE1||' '||E.NOMBRE2 AS "NOMBRES",
E.NOMBRE1 AS "NOMBRE1",
E.NOMBRE2 AS "NOMBRE2",
E.APELLIDO1||' '||E.APELLIDO2 AS "APELLIDOS",
E.APELLIDO1 AS "APELLIDO1",
E.APELLIDO2 AS "APELLIDO2",
E.FECHA_NA AS "FECHA DE NACIMIENTO",
E.NACIONAL AS "NACIONALIDAD",
CASE WHEN E.SEXO = '1' THEN 'M' ELSE 'F' END AS "SEXO",
E.EDO_CIVIL AS "ESTADO CIVIL",
CASE WHEN E.ZURDO = '1' THEN 'Z' ELSE 'D' END AS "HABILIDAD MANUAL",
E.TELEFONO1 AS "TELEFONO1",
E.TELEFONO2 AS "TELEFONO2",
E.E_MAIL1 AS "EMAIL",
E.DIRECCION AS "DIRECCION",
E.CIUDAD AS "CIUDAD",
E.COD_POSTAL AS "CODIGO POSTAL",
B.NRO_RIF
FROM TA_RELACION_PUESTO A,  TA_RELACION_LABORAL B,   EO_PUESTO C,  NM_RELACION_PAGO D,     EO_PERSONA E, NMT038 F, EO_UNIDAD G, NMT002 H, EO_CARGO K--, SPI_PAISES N, SPI_ENTIDAD_FEDERAL O
WHERE A.ID_EMPRESA     =  B.ID_EMPRESA   
AND   A.FICHA          =  B.FICHA 
AND A.ID_EMPRESA       = C.ID_EMPRESA   
AND A.ID_UNIDAD        = C.ID_UNIDAD   
AND A.ID_PUESTO        = C.ID  
AND A.ID_EMPRESA       = D.ID_EMPRESA   
AND A.FICHA            = D.FICHA 
AND D.ID_EMPRESA       = F.CIA_CODCIA  
AND D.ID_DIS_NOMINA    = F.CODSUC
AND B.ID_PERSONA       = E.ID
AND G.ID_EMPRESA       = C.ID_EMPRESA
AND G.ID               = C.ID_UNIDAD
AND H.CIA_CODCIA       = B.ID_EMPRESA
AND H.CODLOC           = B.ID_LOCALIDAD
AND K.ID_EMPRESA = C.ID_EMPRESA
AND K.ID = C.ID_CARGO
AND A.FECHA_FIN IS NULL  
) A  LEFT JOIN NMM007 I ON (I.CIA_CODCIA = A."ENTIDAD DE TRABAJO" AND I.TRAB_FICTRA = A.FICHA) WHERE I.TRAB_FICTRA IS NULL

UNION---------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------
--------------------------------TRABAJADORES CON ALGUNA SITUACION PERO DIFERENTE A VACACIONES Y SUSPENCION----------------------
--------------------------------------------------------------------------------------------------------------------------------

SELECT A.*,
NULL "CODIGO SITUACION",
NULL "SITUACION ACTUAL",
NULL "FECHA INICIO SITUACION", 
NULL "MES INICIO SITUACION",
NULL "FECHA FIN SITUACION"
FROM (SELECT B.ID_EMPRESA AS "ENTIDAD DE TRABAJO",   
D.ID_NOMINA AS "TIPO NOMINA",
A.FICHA,   
E.NUM_IDEN AS "CEDULA",
E.NOMBRE1||' '||E.NOMBRE2||' '||E.APELLIDO1||' '||E.APELLIDO2 AS "NOMBRES Y APELLIDOS",
C.ID_UNIDAD AS "CODIGO DE UNIDAD", 
G.NOMBRE AS "UNIDAD ORGANIZATIVA",
C.ID_CARGO  AS "CODIGO CARGO",     
K.NOMBRE AS "DESCRIPCION CARGO",
SPI_LOOKUP01.sueldo_hist(A.ID_EMPRESA,A.FICHA,'1',sysdate) "SUELDO DIA",
((SPI_LOOKUP01.sueldo_hist(A.ID_EMPRESA,A.FICHA,'1',sysdate)) * 30) "SUELDO",
D.ID_DIS_NOMINA AS "CODIGO DISTRIBUCION NOMINA",     
F.DESSUC "DISTRIBUCION NOMINA",
H.CODLOC "CODIGO LOCALIDAD",
H.DESLO1 "LOCALIDAD",
B.F_INGRESO "FECHA INGRESO",
B.F_CONTRATO "FECHA CONTRATO",
CASE WHEN B.F_RETIRO IS NULL THEN 'ACTIVO' ELSE 'RETIRADO' END AS ESTATUS,
E.NOMBRE1||' '||E.NOMBRE2 AS "NOMBRES",
E.NOMBRE1 AS "NOMBRE1",
E.NOMBRE2 AS "NOMBRE2",
E.APELLIDO1||' '||E.APELLIDO2 AS "APELLIDOS",
E.APELLIDO1 AS "APELLIDO1",
E.APELLIDO2 AS "APELLIDO2",
E.FECHA_NA AS "FECHA DE NACIMIENTO",
E.NACIONAL AS "NACIONALIDAD",
CASE WHEN E.SEXO = '1' THEN 'M' ELSE 'F' END AS "SEXO",
E.EDO_CIVIL AS "ESTADO CIVIL",
CASE WHEN E.ZURDO = '1' THEN 'Z' ELSE 'D' END AS "HABILIDAD MANUAL",
E.TELEFONO1 AS "TELEFONO1",
E.TELEFONO2 AS "TELEFONO2",
E.E_MAIL1 AS "EMAIL",
E.DIRECCION AS "DIRECCION",
E.CIUDAD AS "CIUDAD",
E.COD_POSTAL AS "CODIGO POSTAL",
B.NRO_RIF
FROM TA_RELACION_PUESTO A,  TA_RELACION_LABORAL B,   EO_PUESTO C,  NM_RELACION_PAGO D,     EO_PERSONA E, NMT038 F, EO_UNIDAD G, NMT002 H, EO_CARGO K--, SPI_PAISES N, SPI_ENTIDAD_FEDERAL O 
WHERE A.ID_EMPRESA     =  B.ID_EMPRESA   
AND   A.FICHA          =  B.FICHA 
AND A.ID_EMPRESA       = C.ID_EMPRESA   
AND A.ID_UNIDAD        = C.ID_UNIDAD   
AND A.ID_PUESTO        = C.ID  
AND A.ID_EMPRESA       = D.ID_EMPRESA   
AND A.FICHA            = D.FICHA 
AND D.ID_EMPRESA       = F.CIA_CODCIA  
AND D.ID_DIS_NOMINA    = F.CODSUC
AND B.ID_PERSONA       = E.ID
AND G.ID_EMPRESA       = C.ID_EMPRESA
AND G.ID               = C.ID_UNIDAD
AND H.CIA_CODCIA       = B.ID_EMPRESA
AND H.CODLOC           = B.ID_LOCALIDAD
AND K.ID_EMPRESA = C.ID_EMPRESA
AND K.ID = C.ID_CARGO
AND A.FECHA_FIN IS NULL  
) A  INNER JOIN (SELECT I.* FROM NMM007 I INNER JOIN (SELECT I.CIA_CODCIA,
I.TRAB_FICTRA,
MAX(I.FECINI) FECINI,
MAX(I.FECFIN) FECFIN
FROM NMM007 I 
GROUP BY I.CIA_CODCIA, I.TRAB_FICTRA) K ON (I.CIA_CODCIA = K.CIA_CODCIA AND I.TRAB_FICTRA = K.TRAB_FICTRA AND I.FECINI = K.FECINI AND I.FECFIN = K.FECFIN)) I ON (I.CIA_CODCIA = A."ENTIDAD DE TRABAJO" AND I.TRAB_FICTRA = A.FICHA)
                                                                                                                                                                LEFT JOIN NMT005 J ON (I.CIA_CODCIA = J.CIA_CODCIA AND I.TNOM_TIPNOM = J.TNOM_TIPNOM AND I.STAT_CODSTA = J.CODSTA)
WHERE J.DESSTA NOT IN ('VACACIONES','SUSPENSION')     

UNION---------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------TRABAJADORES SUSPENDIDOS---------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------

SELECT A.*,
NULL "CODIGO SITUACION",
NULL "SITUACION ACTUAL",
NULL "FECHA INICIO SITUACION", 
NULL "MES INICIO SITUACION",
NULL "FECHA FIN SITUACION"
FROM (SELECT B.ID_EMPRESA AS "ENTIDAD DE TRABAJO",   
D.ID_NOMINA AS "TIPO NOMINA",
A.FICHA,   
E.NUM_IDEN AS "CEDULA",
E.NOMBRE1||' '||E.NOMBRE2||' '||E.APELLIDO1||' '||E.APELLIDO2 AS "NOMBRES Y APELLIDOS",
C.ID_UNIDAD AS "CODIGO DE UNIDAD", 
G.NOMBRE AS "UNIDAD ORGANIZATIVA",
C.ID_CARGO  AS "CODIGO CARGO",     
K.NOMBRE AS "DESCRIPCION CARGO",
SPI_LOOKUP01.sueldo_hist(A.ID_EMPRESA,A.FICHA,'1',sysdate) "SUELDO DIA",
((SPI_LOOKUP01.sueldo_hist(A.ID_EMPRESA,A.FICHA,'1',sysdate)) * 30) "SUELDO",
D.ID_DIS_NOMINA AS "CODIGO DISTRIBUCION NOMINA",     
F.DESSUC "DISTRIBUCION NOMINA",
H.CODLOC "CODIGO LOCALIDAD",
H.DESLO1 "LOCALIDAD",
B.F_INGRESO "FECHA INGRESO",
B.F_CONTRATO "FECHA CONTRATO",
CASE WHEN B.F_RETIRO IS NULL THEN 'ACTIVO' ELSE 'RETIRADO' END AS ESTATUS,
E.NOMBRE1||' '||E.NOMBRE2 AS "NOMBRES",
E.NOMBRE1 AS "NOMBRE1",
E.NOMBRE2 AS "NOMBRE2",
E.APELLIDO1||' '||E.APELLIDO2 AS "APELLIDOS",
E.APELLIDO1 AS "APELLIDO1",
E.APELLIDO2 AS "APELLIDO2",
E.FECHA_NA AS "FECHA DE NACIMIENTO",
E.NACIONAL AS "NACIONALIDAD",
CASE WHEN E.SEXO = '1' THEN 'M' ELSE 'F' END AS "SEXO",
E.EDO_CIVIL AS "ESTADO CIVIL",
CASE WHEN E.ZURDO = '1' THEN 'Z' ELSE 'D' END AS "HABILIDAD MANUAL",
E.TELEFONO1 AS "TELEFONO1",
E.TELEFONO2 AS "TELEFONO2",
E.E_MAIL1 AS "EMAIL",
E.DIRECCION AS "DIRECCION",
E.CIUDAD AS "CIUDAD",
E.COD_POSTAL AS "CODIGO POSTAL",
B.NRO_RIF
FROM TA_RELACION_PUESTO A,  TA_RELACION_LABORAL B,   EO_PUESTO C,  NM_RELACION_PAGO D,     EO_PERSONA E, NMT038 F, EO_UNIDAD G, NMT002 H, EO_CARGO K--, SPI_PAISES N, SPI_ENTIDAD_FEDERAL O
WHERE A.ID_EMPRESA     =  B.ID_EMPRESA   
AND   A.FICHA          =  B.FICHA 
AND A.ID_EMPRESA       = C.ID_EMPRESA   
AND A.ID_UNIDAD        = C.ID_UNIDAD   
AND A.ID_PUESTO        = C.ID  
AND A.ID_EMPRESA       = D.ID_EMPRESA   
AND A.FICHA            = D.FICHA 
AND D.ID_EMPRESA       = F.CIA_CODCIA  
AND D.ID_DIS_NOMINA    = F.CODSUC
AND B.ID_PERSONA       = E.ID
AND G.ID_EMPRESA       = C.ID_EMPRESA
AND G.ID               = C.ID_UNIDAD
AND H.CIA_CODCIA       = B.ID_EMPRESA
AND H.CODLOC           = B.ID_LOCALIDAD
AND K.ID_EMPRESA = C.ID_EMPRESA
AND K.ID = C.ID_CARGO
AND A.FECHA_FIN IS NULL 
) A  LEFT JOIN NMM007 I ON (I.CIA_CODCIA = A."ENTIDAD DE TRABAJO" AND I.TRAB_FICTRA = A.FICHA)
                            LEFT JOIN NMT005 J ON (I.CIA_CODCIA = J.CIA_CODCIA AND I.TNOM_TIPNOM = J.TNOM_TIPNOM AND I.STAT_CODSTA = J.CODSTA)
WHERE J.DESSTA IN ('SUSPENSION')

UNION---------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------
----------------------------------------TRABAJADORES A LA FECHA SYSDATE EN VACACIONES-------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------

SELECT A.*,
NULL "CODIGO SITUACION",
NULL "SITUACION ACTUAL",
NULL "FECHA INICIO SITUACION", 
NULL "MES INICIO SITUACION",
NULL "FECHA FIN SITUACION"
FROM (SELECT B.ID_EMPRESA AS "ENTIDAD DE TRABAJO",   
D.ID_NOMINA AS "TIPO NOMINA",
A.FICHA,   
E.NUM_IDEN AS "CEDULA",
E.NOMBRE1||' '||E.NOMBRE2||' '||E.APELLIDO1||' '||E.APELLIDO2 AS "NOMBRES Y APELLIDOS",
C.ID_UNIDAD AS "CODIGO DE UNIDAD", 
G.NOMBRE AS "UNIDAD ORGANIZATIVA",
C.ID_CARGO  AS "CODIGO CARGO",     
K.NOMBRE AS "DESCRIPCION CARGO",
SPI_LOOKUP01.sueldo_hist(A.ID_EMPRESA,A.FICHA,'1',sysdate) "SUELDO DIA",
((SPI_LOOKUP01.sueldo_hist(A.ID_EMPRESA,A.FICHA,'1',sysdate)) * 30) "SUELDO",
D.ID_DIS_NOMINA AS "CODIGO DISTRIBUCION NOMINA",     
F.DESSUC "DISTRIBUCION NOMINA",
H.CODLOC "CODIGO LOCALIDAD",
H.DESLO1 "LOCALIDAD",
B.F_INGRESO "FECHA INGRESO",
B.F_CONTRATO "FECHA CONTRATO",
CASE WHEN B.F_RETIRO IS NULL THEN 'ACTIVO' ELSE 'RETIRADO' END AS ESTATUS,
E.NOMBRE1||' '||E.NOMBRE2 AS "NOMBRES",
E.NOMBRE1 AS "NOMBRE1",
E.NOMBRE2 AS "NOMBRE2",
E.APELLIDO1||' '||E.APELLIDO2 AS "APELLIDOS",
E.APELLIDO1 AS "APELLIDO1",
E.APELLIDO2 AS "APELLIDO2",
E.FECHA_NA AS "FECHA DE NACIMIENTO",
E.NACIONAL AS "NACIONALIDAD",
CASE WHEN E.SEXO = '1' THEN 'M' ELSE 'F' END AS "SEXO",
E.EDO_CIVIL AS "ESTADO CIVIL",
CASE WHEN E.ZURDO = '1' THEN 'Z' ELSE 'D' END AS "HABILIDAD MANUAL",
E.TELEFONO1 AS "TELEFONO1",
E.TELEFONO2 AS "TELEFONO2",
E.E_MAIL1 AS "EMAIL",
E.DIRECCION AS "DIRECCION",
E.CIUDAD AS "CIUDAD",
E.COD_POSTAL AS "CODIGO POSTAL",
B.NRO_RIF
FROM TA_RELACION_PUESTO A,  TA_RELACION_LABORAL B,   EO_PUESTO C,  NM_RELACION_PAGO D,     EO_PERSONA E, NMT038 F, EO_UNIDAD G, NMT002 H, EO_CARGO K --, SPI_PAISES N, SPI_ENTIDAD_FEDERAL O
WHERE A.ID_EMPRESA     =  B.ID_EMPRESA   
AND   A.FICHA          =  B.FICHA 
AND A.ID_EMPRESA       = C.ID_EMPRESA   
AND A.ID_UNIDAD        = C.ID_UNIDAD   
AND A.ID_PUESTO        = C.ID  
AND A.ID_EMPRESA       = D.ID_EMPRESA   
AND A.FICHA            = D.FICHA 
AND D.ID_EMPRESA       = F.CIA_CODCIA  
AND D.ID_DIS_NOMINA    = F.CODSUC
AND B.ID_PERSONA       = E.ID
AND G.ID_EMPRESA       = C.ID_EMPRESA
AND G.ID               = C.ID_UNIDAD
AND H.CIA_CODCIA       = B.ID_EMPRESA
AND H.CODLOC           = B.ID_LOCALIDAD
AND K.ID_EMPRESA = C.ID_EMPRESA
AND K.ID = C.ID_CARGO
AND A.FECHA_FIN IS NULL  
) A  LEFT JOIN NMM007 I ON (I.CIA_CODCIA = A."ENTIDAD DE TRABAJO" AND I.TRAB_FICTRA = A.FICHA)
                            LEFT JOIN NMT005 J ON (I.CIA_CODCIA = J.CIA_CODCIA AND I.TNOM_TIPNOM = J.TNOM_TIPNOM AND I.STAT_CODSTA = J.CODSTA)
WHERE J.DESSTA IN ('VACACIONES')
AND SYSDATE BETWEEN I.FECINI AND I.FECFIN

UNION---------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------
------TRABAJADORES CON SITUACION VACACIONES PERO DIFERENTE A LA FECHA SYSDATE Y QUE VACACIONES SEA SU ULTIMA SITUACION----------
--------------------------------------------------------------------------------------------------------------------------------

SELECT A.*,
NULL "CODIGO SITUACION",
NULL "SITUACION ACTUAL",
NULL "FECHA INICIO SITUACION", 
NULL "MES INICIO SITUACION",
NULL "FECHA FIN SITUACION"
FROM (SELECT B.ID_EMPRESA AS "ENTIDAD DE TRABAJO",   
D.ID_NOMINA AS "TIPO NOMINA",
A.FICHA,   
E.NUM_IDEN AS "CEDULA",
E.NOMBRE1||' '||E.NOMBRE2||' '||E.APELLIDO1||' '||E.APELLIDO2 AS "NOMBRES Y APELLIDOS",
C.ID_UNIDAD AS "CODIGO DE UNIDAD", 
G.NOMBRE AS "UNIDAD ORGANIZATIVA",
C.ID_CARGO  AS "CODIGO CARGO",     
K.NOMBRE AS "DESCRIPCION CARGO",
SPI_LOOKUP01.sueldo_hist(A.ID_EMPRESA,A.FICHA,'1',sysdate) "SUELDO DIA",
((SPI_LOOKUP01.sueldo_hist(A.ID_EMPRESA,A.FICHA,'1',sysdate)) * 30) "SUELDO",
D.ID_DIS_NOMINA AS "CODIGO DISTRIBUCION NOMINA",     
F.DESSUC "DISTRIBUCION NOMINA",
H.CODLOC "CODIGO LOCALIDAD",
H.DESLO1 "LOCALIDAD",
B.F_INGRESO "FECHA INGRESO",
B.F_CONTRATO "FECHA CONTRATO",
CASE WHEN B.F_RETIRO IS NULL THEN 'ACTIVO' ELSE 'RETIRADO' END AS ESTATUS,
E.NOMBRE1||' '||E.NOMBRE2 AS "NOMBRES",
E.NOMBRE1 AS "NOMBRE1",
E.NOMBRE2 AS "NOMBRE2",
E.APELLIDO1||' '||E.APELLIDO2 AS "APELLIDOS",
E.APELLIDO1 AS "APELLIDO1",
E.APELLIDO2 AS "APELLIDO2",
E.FECHA_NA AS "FECHA DE NACIMIENTO",
E.NACIONAL AS "NACIONALIDAD",
CASE WHEN E.SEXO = '1' THEN 'M' ELSE 'F' END AS "SEXO",
E.EDO_CIVIL AS "ESTADO CIVIL",
CASE WHEN E.ZURDO = '1' THEN 'Z' ELSE 'D' END AS "HABILIDAD MANUAL",
E.TELEFONO1 AS "TELEFONO1",
E.TELEFONO2 AS "TELEFONO2",
E.E_MAIL1 AS "EMAIL",
E.DIRECCION AS "DIRECCION",
E.CIUDAD AS "CIUDAD",
E.COD_POSTAL AS "CODIGO POSTAL",
B.NRO_RIF
FROM TA_RELACION_PUESTO A,  TA_RELACION_LABORAL B,   EO_PUESTO C,  NM_RELACION_PAGO D,     EO_PERSONA E, NMT038 F, EO_UNIDAD G, NMT002 H, EO_CARGO K--, SPI_PAISES N, SPI_ENTIDAD_FEDERAL O
WHERE A.ID_EMPRESA     =  B.ID_EMPRESA   
AND   A.FICHA          =  B.FICHA 
AND A.ID_EMPRESA       = C.ID_EMPRESA   
AND A.ID_UNIDAD        = C.ID_UNIDAD   
AND A.ID_PUESTO        = C.ID  
AND A.ID_EMPRESA       = D.ID_EMPRESA   
AND A.FICHA            = D.FICHA 
AND D.ID_EMPRESA       = F.CIA_CODCIA  
AND D.ID_DIS_NOMINA    = F.CODSUC
AND B.ID_PERSONA       = E.ID
AND G.ID_EMPRESA       = C.ID_EMPRESA
AND G.ID               = C.ID_UNIDAD
AND H.CIA_CODCIA       = B.ID_EMPRESA
AND H.CODLOC           = B.ID_LOCALIDAD
AND K.ID_EMPRESA = C.ID_EMPRESA
AND K.ID = C.ID_CARGO
AND A.FECHA_FIN IS NULL   
) A  INNER JOIN (SELECT I.* FROM NMM007 I INNER JOIN (SELECT I.CIA_CODCIA,
I.TRAB_FICTRA,
MAX(I.FECINI) FECINI,
MAX(I.FECFIN) FECFIN
FROM NMM007 I 
GROUP BY I.CIA_CODCIA, I.TRAB_FICTRA) K ON (I.CIA_CODCIA = K.CIA_CODCIA AND I.TRAB_FICTRA = K.TRAB_FICTRA AND I.FECINI = K.FECINI AND I.FECFIN = K.FECFIN)) I ON (I.CIA_CODCIA = A."ENTIDAD DE TRABAJO" AND I.TRAB_FICTRA = A.FICHA)
                                                                                                                                                                LEFT JOIN NMT005 J ON (I.CIA_CODCIA = J.CIA_CODCIA AND I.TNOM_TIPNOM = J.TNOM_TIPNOM AND I.STAT_CODSTA = J.CODSTA)
WHERE J.DESSTA IN ('VACACIONES')                                                                                                                                                                
AND SYSDATE NOT BETWEEN I.FECINI AND I.FECFIN
) A 
ORDER BY "ENTIDAD DE TRABAJO", "FICHA"
