
-- LISTAR USUARIOS QUE TIENEN ACCESO A LAS BASES DE DATOS --
SELECT user FROM mysql.user;

-- LISTAR USUARIO E IP DE LA CUAL TIENEN ACCESO A LA BASE DE DATOS --
SELECT user, host FROM mysql.user ORDER BY user;

-- MOSTRAS PRIVILEGIOS POR USUARIO --
SHOW GRANTS FOR ycolmenarez;

-- LISTAR PRIVILEGIOS POR UNA BASE DE DATOS EN ESPECIFICO --
SELECT user,host,select_priv FROM mysql.db WHERE db='spi_bi';

-- LISTAR PERMISOLOGIAS POR USUARIOS POR UNA BASE DE DATOS EN ESPECIFICO --
SELECT user,host,insert_priv,update_priv,delete_priv FROM mysql.db WHERE db='spi_bi';

-- LISTAR PRIVILEGIOS DE BASE DE DATOS --
DESCRIBE mysql.db;
SHOW PRIVILEGES;